# Generated by Django 5.1 on 2025-06-01 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("books", "0001_initial"),
        ("borrowings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="borrowing_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="borrowings.borrowing"
            ),
        ),
    ]
